source 'https://rubygems.org'
r_name = 'https://github.com/zaki1993/Ruby-Project/lisp-interpreter'
git_source(:github) { |_repo_name| r_name }

# Specify your gem's dependencies in lisp-interpreter.gemspec
gemspec
