source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{zaki1993/Ruby-Project/lisp-interpreter}" }

# Specify your gem's dependencies in lisp-interpreter.gemspec
gemspec
